---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '11.4.0'

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: system_install
  run_list:
    - recipe[identify::system_install]
    - recipe[minitest-handler]
  attributes: 
    identify:
      color: red
- name: node_name
  run_list:
    - recipe[identify::system_install]
    - recipe[minitest-handler]
  attributes:
    identify:
      color: blue
      use_node_name: true
